# Please refer to the file comments in `ci.yml` for more information.
name: ci

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  skip-changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            go:
              - Makefile
              - go.*
              - '**.go'
              - 'helm/**'
            ui:
              - 'ui/yarn.lock'
              - '**.js'
              - '**.ts'
              - '**.tsx'
  go:
    needs: skip-changes
    if: ${{ needs.skip-changes.outputs.go != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        job:
          - verify
          - build
          - test
    runs-on: ${{ fromJson('{"amd64":"ubuntu-latest", "arm64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}
    steps:
      - run: echo "Not required"
  ui:
    needs: skip-changes
    if: ${{ needs.skip-changes.outputs.ui != 'true' }}
    strategy:
      matrix:
        job:
          - verify
          - build
          - test
    runs-on: "ubuntu-latest"
    steps:
      - run: echo "Not required"
